# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QSpacerItem,
    QStatusBar, QToolBar, QWidget)
import buttonresource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon = QIcon()
        icon.addFile(u":/Buttons/glassButtonAbout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon)
        self.actionAndroid = QAction(MainWindow)
        self.actionAndroid.setObjectName(u"actionAndroid")
        icon1 = QIcon()
        icon1.addFile(u":/Buttons/glassButtonAndroid.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAndroid.setIcon(icon1)
        self.actionApacheWebServer = QAction(MainWindow)
        self.actionApacheWebServer.setObjectName(u"actionApacheWebServer")
        icon2 = QIcon()
        icon2.addFile(u":/Buttons/glassButtonApacheWebServer.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionApacheWebServer.setIcon(icon2)
        self.actionArduino = QAction(MainWindow)
        self.actionArduino.setObjectName(u"actionArduino")
        icon3 = QIcon()
        icon3.addFile(u":/Buttons/glassButtonArduino.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionArduino.setIcon(icon3)
        self.actionBash = QAction(MainWindow)
        self.actionBash.setObjectName(u"actionBash")
        icon4 = QIcon()
        icon4.addFile(u":/Buttons/glassButtonBash.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBash.setIcon(icon4)
        self.actionC = QAction(MainWindow)
        self.actionC.setObjectName(u"actionC")
        icon5 = QIcon()
        icon5.addFile(u":/Buttons/glassButtonC.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionC.setIcon(icon5)
        self.actionCpp = QAction(MainWindow)
        self.actionCpp.setObjectName(u"actionCpp")
        icon6 = QIcon()
        icon6.addFile(u":/Buttons/glassButtonC++.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCpp.setIcon(icon6)
        self.actionCancel = QAction(MainWindow)
        self.actionCancel.setObjectName(u"actionCancel")
        icon7 = QIcon()
        icon7.addFile(u":/Buttons/glassButtonCancel.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCancel.setIcon(icon7)
        self.actionClear = QAction(MainWindow)
        self.actionClear.setObjectName(u"actionClear")
        icon8 = QIcon()
        icon8.addFile(u":/Buttons/glassButtonClear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClear.setIcon(icon8)
        self.actionCMake = QAction(MainWindow)
        self.actionCMake.setObjectName(u"actionCMake")
        icon9 = QIcon()
        icon9.addFile(u":/Buttons/glassButtonCMake.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCMake.setIcon(icon9)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon10 = QIcon()
        icon10.addFile(u":/Buttons/glassButtonCopy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon10)
        self.actionCSS = QAction(MainWindow)
        self.actionCSS.setObjectName(u"actionCSS")
        icon11 = QIcon()
        icon11.addFile(u":/Buttons/glassButtonCSS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCSS.setIcon(icon11)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon12 = QIcon()
        icon12.addFile(u":/Buttons/glassButtonCut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon12)
        self.actionDoxygen = QAction(MainWindow)
        self.actionDoxygen.setObjectName(u"actionDoxygen")
        icon13 = QIcon()
        icon13.addFile(u":/Buttons/glassButtonDoxygen.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDoxygen.setIcon(icon13)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon14 = QIcon()
        icon14.addFile(u":/Buttons/glassButtonExit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon14)
        self.actionGit = QAction(MainWindow)
        self.actionGit.setObjectName(u"actionGit")
        icon15 = QIcon()
        icon15.addFile(u":/Buttons/glassButtonGit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGit.setIcon(icon15)
        self.actionGitHub = QAction(MainWindow)
        self.actionGitHub.setObjectName(u"actionGitHub")
        icon16 = QIcon()
        icon16.addFile(u":/Buttons/glassButtonGitHub.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGitHub.setIcon(icon16)
        self.actionGraphViz = QAction(MainWindow)
        self.actionGraphViz.setObjectName(u"actionGraphViz")
        icon17 = QIcon()
        icon17.addFile(u":/Buttons/glassButtonGraphViz.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionGraphViz.setIcon(icon17)
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        icon18 = QIcon()
        icon18.addFile(u":/Buttons/glassButtonHelp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHelp.setIcon(icon18)
        self.actionHTML = QAction(MainWindow)
        self.actionHTML.setObjectName(u"actionHTML")
        icon19 = QIcon()
        icon19.addFile(u":/Buttons/glassButtonHtml.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHTML.setIcon(icon19)
        self.actionImages = QAction(MainWindow)
        self.actionImages.setObjectName(u"actionImages")
        icon20 = QIcon()
        icon20.addFile(u":/Buttons/glassButtonImages.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionImages.setIcon(icon20)
        self.actioniOS = QAction(MainWindow)
        self.actioniOS.setObjectName(u"actioniOS")
        icon21 = QIcon()
        icon21.addFile(u":/Buttons/glassButtonIos.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actioniOS.setIcon(icon21)
        self.actionJava = QAction(MainWindow)
        self.actionJava.setObjectName(u"actionJava")
        icon22 = QIcon()
        icon22.addFile(u":/Buttons/glassButtonJava.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionJava.setIcon(icon22)
        self.actionKDoc = QAction(MainWindow)
        self.actionKDoc.setObjectName(u"actionKDoc")
        icon23 = QIcon()
        icon23.addFile(u":/Buttons/glassButtonKDoc.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionKDoc.setIcon(icon23)
        self.actionKotlin = QAction(MainWindow)
        self.actionKotlin.setObjectName(u"actionKotlin")
        icon24 = QIcon()
        icon24.addFile(u":/Buttons/glassButtonKotlin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionKotlin.setIcon(icon24)
        self.actionList = QAction(MainWindow)
        self.actionList.setObjectName(u"actionList")
        icon25 = QIcon()
        icon25.addFile(u":/Buttons/glassButtonList.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionList.setIcon(icon25)
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        icon26 = QIcon()
        icon26.addFile(u":/Buttons/glassButtonLoad.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionLoad.setIcon(icon26)
        self.actionMySql = QAction(MainWindow)
        self.actionMySql.setObjectName(u"actionMySql")
        icon27 = QIcon()
        icon27.addFile(u":/Buttons/glassButtonMySql.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMySql.setIcon(icon27)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon28 = QIcon()
        icon28.addFile(u":/Buttons/glassButtonNew.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon28)
        self.actionNo = QAction(MainWindow)
        self.actionNo.setObjectName(u"actionNo")
        icon29 = QIcon()
        icon29.addFile(u":/Buttons/glassButtonNo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNo.setIcon(icon29)
        self.actionOverWrite = QAction(MainWindow)
        self.actionOverWrite.setObjectName(u"actionOverWrite")
        icon30 = QIcon()
        icon30.addFile(u":/Buttons/glassButtonOverWrite.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOverWrite.setIcon(icon30)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon31 = QIcon()
        icon31.addFile(u":/Buttons/glassButtonPaste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon31)
        self.actionPhp = QAction(MainWindow)
        self.actionPhp.setObjectName(u"actionPhp")
        icon32 = QIcon()
        icon32.addFile(u":/Buttons/glassButtonPhp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPhp.setIcon(icon32)
        self.actionPostgreSql = QAction(MainWindow)
        self.actionPostgreSql.setObjectName(u"actionPostgreSql")
        icon33 = QIcon()
        icon33.addFile(u":/Buttons/glassButtonPostgreSql.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPostgreSql.setIcon(icon33)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon34 = QIcon()
        icon34.addFile(u":/Buttons/glassButtonPrint.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint.setIcon(icon34)
        self.actionPython = QAction(MainWindow)
        self.actionPython.setObjectName(u"actionPython")
        icon35 = QIcon()
        icon35.addFile(u":/Buttons/glassButtonPython.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPython.setIcon(icon35)
        self.actionQt = QAction(MainWindow)
        self.actionQt.setObjectName(u"actionQt")
        icon36 = QIcon()
        icon36.addFile(u":/Buttons/glassButtonQt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQt.setIcon(icon36)
        self.actionQtAbout = QAction(MainWindow)
        self.actionQtAbout.setObjectName(u"actionQtAbout")
        icon37 = QIcon()
        icon37.addFile(u":/Buttons/glassButtonQtAbout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQtAbout.setIcon(icon37)
        self.actionQtDesigner = QAction(MainWindow)
        self.actionQtDesigner.setObjectName(u"actionQtDesigner")
        icon38 = QIcon()
        icon38.addFile(u":/Buttons/glassButtonQtDesigner.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQtDesigner.setIcon(icon38)
        self.actionQtPython = QAction(MainWindow)
        self.actionQtPython.setObjectName(u"actionQtPython")
        icon39 = QIcon()
        icon39.addFile(u":/Buttons/glassButtonQtPython.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQtPython.setIcon(icon39)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon40 = QIcon()
        icon40.addFile(u":/Buttons/glassButtonQuit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon40)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon41 = QIcon()
        icon41.addFile(u":/Buttons/glassButtonRedo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon41)
        self.actionRename = QAction(MainWindow)
        self.actionRename.setObjectName(u"actionRename")
        icon42 = QIcon()
        icon42.addFile(u":/Buttons/glassButtonRename.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRename.setIcon(icon42)
        self.actionReset = QAction(MainWindow)
        self.actionReset.setObjectName(u"actionReset")
        icon43 = QIcon()
        icon43.addFile(u":/Buttons/glassButtonReset.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReset.setIcon(icon43)
        self.actionResourceCompiler = QAction(MainWindow)
        self.actionResourceCompiler.setObjectName(u"actionResourceCompiler")
        icon44 = QIcon()
        icon44.addFile(u":/Buttons/glassButtonResourceCompiler.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionResourceCompiler.setIcon(icon44)
        self.actionRun = QAction(MainWindow)
        self.actionRun.setObjectName(u"actionRun")
        icon45 = QIcon()
        icon45.addFile(u":/Buttons/glassButtonRun.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRun.setIcon(icon45)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon46 = QIcon()
        icon46.addFile(u":/Buttons/glassButtonSave.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon46)
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        icon47 = QIcon()
        icon47.addFile(u":/Buttons/glassButtonSaveAs.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveAs.setIcon(icon47)
        self.actionScript = QAction(MainWindow)
        self.actionScript.setObjectName(u"actionScript")
        icon48 = QIcon()
        icon48.addFile(u":/Buttons/glassButtonScript.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionScript.setIcon(icon48)
        self.actionSelect = QAction(MainWindow)
        self.actionSelect.setObjectName(u"actionSelect")
        icon49 = QIcon()
        icon49.addFile(u":/Buttons/glassButtonSelect.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSelect.setIcon(icon49)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon50 = QIcon()
        icon50.addFile(u":/Buttons/glassButtonSettings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSettings.setIcon(icon50)
        self.actionSqlLite = QAction(MainWindow)
        self.actionSqlLite.setObjectName(u"actionSqlLite")
        icon51 = QIcon()
        icon51.addFile(u":/Buttons/glassButtonSqllite.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSqlLite.setIcon(icon51)
        self.actionStart = QAction(MainWindow)
        self.actionStart.setObjectName(u"actionStart")
        icon52 = QIcon()
        icon52.addFile(u":/Buttons/glassButtonStart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStart.setIcon(icon52)
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        icon53 = QIcon()
        icon53.addFile(u":/Buttons/glassButtonStop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStop.setIcon(icon53)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon54 = QIcon()
        icon54.addFile(u":/Buttons/glassButtonUndo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon54)
        self.actionUsb = QAction(MainWindow)
        self.actionUsb.setObjectName(u"actionUsb")
        icon55 = QIcon()
        icon55.addFile(u":/Buttons/glassButtonUsb.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUsb.setIcon(icon55)
        self.actionUserInterface = QAction(MainWindow)
        self.actionUserInterface.setObjectName(u"actionUserInterface")
        icon56 = QIcon()
        icon56.addFile(u":/Buttons/glassButtonUserInterface.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUserInterface.setIcon(icon56)
        self.actionVSCode = QAction(MainWindow)
        self.actionVSCode.setObjectName(u"actionVSCode")
        icon57 = QIcon()
        icon57.addFile(u":/Buttons/glassButtonVSCode.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionVSCode.setIcon(icon57)
        self.actionWrite = QAction(MainWindow)
        self.actionWrite.setObjectName(u"actionWrite")
        icon58 = QIcon()
        icon58.addFile(u":/Buttons/glassButtonWrite.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWrite.setIcon(icon58)
        self.actionWww = QAction(MainWindow)
        self.actionWww.setObjectName(u"actionWww")
        icon59 = QIcon()
        icon59.addFile(u":/Buttons/glassButtonWWW.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionWww.setIcon(icon59)
        self.actionYes = QAction(MainWindow)
        self.actionYes.setObjectName(u"actionYes")
        icon60 = QIcon()
        icon60.addFile(u":/Buttons/glassButtonYes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionYes.setIcon(icon60)
        self.actionAbort = QAction(MainWindow)
        self.actionAbort.setObjectName(u"actionAbort")
        icon61 = QIcon()
        icon61.addFile(u":/Buttons/glassButtonAbort.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbort.setIcon(icon61)
        self.actionConfigure = QAction(MainWindow)
        self.actionConfigure.setObjectName(u"actionConfigure")
        icon62 = QIcon()
        icon62.addFile(u":/Buttons/glassButtonConfigure.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionConfigure.setIcon(icon62)
        self.actionDia = QAction(MainWindow)
        self.actionDia.setObjectName(u"actionDia")
        icon63 = QIcon()
        icon63.addFile(u":/Buttons/glassButtonDia.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionDia.setIcon(icon63)
        self.actionPyQt = QAction(MainWindow)
        self.actionPyQt.setObjectName(u"actionPyQt")
        icon64 = QIcon()
        icon64.addFile(u":/Buttons/glassButtonPyQt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPyQt.setIcon(icon64)
        self.actionPySide = QAction(MainWindow)
        self.actionPySide.setObjectName(u"actionPySide")
        icon65 = QIcon()
        icon65.addFile(u":/Buttons/glassButtonPySide.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPySide.setIcon(icon65)
        self.actionMinimise = QAction(MainWindow)
        self.actionMinimise.setObjectName(u"actionMinimise")
        icon66 = QIcon()
        icon66.addFile(u":/Buttons/glassButtonMinimise.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMinimise.setIcon(icon66)
        self.actionMaximise = QAction(MainWindow)
        self.actionMaximise.setObjectName(u"actionMaximise")
        icon67 = QIcon()
        icon67.addFile(u":/Buttons/glassButtonMaximise.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMaximise.setIcon(icon67)
        self.actionContextHelp = QAction(MainWindow)
        self.actionContextHelp.setObjectName(u"actionContextHelp")
        self.actionSetUp = QAction(MainWindow)
        self.actionSetUp.setObjectName(u"actionSetUp")
        icon68 = QIcon()
        icon68.addFile(u":/Buttons/glassButtonSetUp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSetUp.setIcon(icon68)
        self.actionMenuMinimise = QAction(MainWindow)
        self.actionMenuMinimise.setObjectName(u"actionMenuMinimise")
        self.actionMenuMaximise = QAction(MainWindow)
        self.actionMenuMaximise.setObjectName(u"actionMenuMaximise")
        self.actionMenuContextHelp = QAction(MainWindow)
        self.actionMenuContextHelp.setObjectName(u"actionMenuContextHelp")
        self.actionMenuExit = QAction(MainWindow)
        self.actionMenuExit.setObjectName(u"actionMenuExit")
        self.actionMenuCopy = QAction(MainWindow)
        self.actionMenuCopy.setObjectName(u"actionMenuCopy")
        self.actionMenuCut = QAction(MainWindow)
        self.actionMenuCut.setObjectName(u"actionMenuCut")
        self.actionMenuPaste = QAction(MainWindow)
        self.actionMenuPaste.setObjectName(u"actionMenuPaste")
        self.actionMenuRedo = QAction(MainWindow)
        self.actionMenuRedo.setObjectName(u"actionMenuRedo")
        self.actionMenuUndo = QAction(MainWindow)
        self.actionMenuUndo.setObjectName(u"actionMenuUndo")
        self.actionMenuClear = QAction(MainWindow)
        self.actionMenuClear.setObjectName(u"actionMenuClear")
        self.actionMenuSelectAll = QAction(MainWindow)
        self.actionMenuSelectAll.setObjectName(u"actionMenuSelectAll")
        self.actionMenuSave = QAction(MainWindow)
        self.actionMenuSave.setObjectName(u"actionMenuSave")
        self.actionMenuSaveAs = QAction(MainWindow)
        self.actionMenuSaveAs.setObjectName(u"actionMenuSaveAs")
        self.actionMenuConfigure = QAction(MainWindow)
        self.actionMenuConfigure.setObjectName(u"actionMenuConfigure")
        self.actionMenuAbout = QAction(MainWindow)
        self.actionMenuAbout.setObjectName(u"actionMenuAbout")
        self.actionMenuAboutQt = QAction(MainWindow)
        self.actionMenuAboutQt.setObjectName(u"actionMenuAboutQt")
        self.actionMenuRun = QAction(MainWindow)
        self.actionMenuRun.setObjectName(u"actionMenuRun")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(50, 220, 721, 80))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEditLeft = QLineEdit(self.horizontalLayoutWidget)
        self.lineEditLeft.setObjectName(u"lineEditLeft")

        self.horizontalLayout.addWidget(self.lineEditLeft)

        self.horizontalSpacer = QSpacerItem(168, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.lineEditRight = QLineEdit(self.horizontalLayoutWidget)
        self.lineEditRight.setObjectName(u"lineEditRight")

        self.horizontalLayout.addWidget(self.lineEditRight)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubarStandard = QMenuBar(MainWindow)
        self.menubarStandard.setObjectName(u"menubarStandard")
        self.menubarStandard.setGeometry(QRect(0, 0, 800, 22))
        self.menu_File = QMenu(self.menubarStandard)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubarStandard)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu_Settings = QMenu(self.menubarStandard)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Window = QMenu(self.menubarStandard)
        self.menu_Window.setObjectName(u"menu_Window")
        self.menu_Help = QMenu(self.menubarStandard)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menu_Build = QMenu(self.menubarStandard)
        self.menu_Build.setObjectName(u"menu_Build")
        MainWindow.setMenuBar(self.menubarStandard)
        self.statusbarStandard = QStatusBar(MainWindow)
        self.statusbarStandard.setObjectName(u"statusbarStandard")
        MainWindow.setStatusBar(self.statusbarStandard)
        self.toolBarSmall = QToolBar(MainWindow)
        self.toolBarSmall.setObjectName(u"toolBarSmall")
        self.toolBarSmall.setMinimumSize(QSize(0, 0))
        self.toolBarSmall.setCursor(QCursor(Qt.PointingHandCursor))
        self.toolBarSmall.setMovable(False)
        self.toolBarSmall.setIconSize(QSize(64, 64))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBarSmall)

        self.menubarStandard.addAction(self.menu_File.menuAction())
        self.menubarStandard.addAction(self.menu_Edit.menuAction())
        self.menubarStandard.addAction(self.menu_Settings.menuAction())
        self.menubarStandard.addAction(self.menu_Build.menuAction())
        self.menubarStandard.addAction(self.menu_Window.menuAction())
        self.menubarStandard.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.actionMenuSave)
        self.menu_File.addAction(self.actionMenuSaveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionMenuExit)
        self.menu_Edit.addAction(self.actionMenuCopy)
        self.menu_Edit.addAction(self.actionMenuCut)
        self.menu_Edit.addAction(self.actionMenuPaste)
        self.menu_Edit.addAction(self.actionMenuClear)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionMenuRedo)
        self.menu_Edit.addAction(self.actionMenuUndo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionMenuSelectAll)
        self.menu_Settings.addAction(self.actionMenuConfigure)
        self.menu_Window.addAction(self.actionMenuMinimise)
        self.menu_Window.addAction(self.actionMenuMaximise)
        self.menu_Help.addAction(self.actionMenuContextHelp)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionMenuAbout)
        self.menu_Help.addAction(self.actionMenuAboutQt)
        self.menu_Build.addAction(self.actionMenuRun)
        self.toolBarSmall.addAction(self.actionExit)
        self.toolBarSmall.addSeparator()
        self.toolBarSmall.addAction(self.actionSave)
        self.toolBarSmall.addSeparator()
        self.toolBarSmall.addAction(self.actionCut)
        self.toolBarSmall.addAction(self.actionCopy)
        self.toolBarSmall.addAction(self.actionPaste)
        self.toolBarSmall.addAction(self.actionRedo)
        self.toolBarSmall.addAction(self.actionUndo)
        self.toolBarSmall.addSeparator()
        self.toolBarSmall.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Buttons and Actions Template", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(tooltip)
        self.actionAbout.setToolTip(QCoreApplication.translate("MainWindow", u"About", None))
#endif // QT_CONFIG(tooltip)
        self.actionAndroid.setText(QCoreApplication.translate("MainWindow", u"Android", None))
#if QT_CONFIG(tooltip)
        self.actionAndroid.setToolTip(QCoreApplication.translate("MainWindow", u"Android", None))
#endif // QT_CONFIG(tooltip)
        self.actionApacheWebServer.setText(QCoreApplication.translate("MainWindow", u"Apache Web Server", None))
#if QT_CONFIG(tooltip)
        self.actionApacheWebServer.setToolTip(QCoreApplication.translate("MainWindow", u"Apache Web Server", None))
#endif // QT_CONFIG(tooltip)
        self.actionArduino.setText(QCoreApplication.translate("MainWindow", u"Arduino", None))
#if QT_CONFIG(tooltip)
        self.actionArduino.setToolTip(QCoreApplication.translate("MainWindow", u"Arduino", None))
#endif // QT_CONFIG(tooltip)
        self.actionBash.setText(QCoreApplication.translate("MainWindow", u"Bash", None))
#if QT_CONFIG(tooltip)
        self.actionBash.setToolTip(QCoreApplication.translate("MainWindow", u"Bash", None))
#endif // QT_CONFIG(tooltip)
        self.actionC.setText(QCoreApplication.translate("MainWindow", u"C", None))
#if QT_CONFIG(tooltip)
        self.actionC.setToolTip(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(tooltip)
        self.actionCpp.setText(QCoreApplication.translate("MainWindow", u"C++", None))
#if QT_CONFIG(tooltip)
        self.actionCpp.setToolTip(QCoreApplication.translate("MainWindow", u"C++", None))
#endif // QT_CONFIG(tooltip)
        self.actionCancel.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
#if QT_CONFIG(tooltip)
        self.actionCancel.setToolTip(QCoreApplication.translate("MainWindow", u"Cancel", None))
#endif // QT_CONFIG(tooltip)
        self.actionClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
#if QT_CONFIG(tooltip)
        self.actionClear.setToolTip(QCoreApplication.translate("MainWindow", u"Clear", None))
#endif // QT_CONFIG(tooltip)
        self.actionCMake.setText(QCoreApplication.translate("MainWindow", u"CMake", None))
#if QT_CONFIG(tooltip)
        self.actionCMake.setToolTip(QCoreApplication.translate("MainWindow", u"CMake", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(tooltip)
        self.actionCopy.setToolTip(QCoreApplication.translate("MainWindow", u"Copy", None))
#endif // QT_CONFIG(tooltip)
        self.actionCSS.setText(QCoreApplication.translate("MainWindow", u"CSS", None))
#if QT_CONFIG(tooltip)
        self.actionCSS.setToolTip(QCoreApplication.translate("MainWindow", u"CSS", None))
#endif // QT_CONFIG(tooltip)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(tooltip)
        self.actionCut.setToolTip(QCoreApplication.translate("MainWindow", u"Cut", None))
#endif // QT_CONFIG(tooltip)
        self.actionDoxygen.setText(QCoreApplication.translate("MainWindow", u"Doxygen", None))
#if QT_CONFIG(tooltip)
        self.actionDoxygen.setToolTip(QCoreApplication.translate("MainWindow", u"Doxygen", None))
#endif // QT_CONFIG(tooltip)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit", None))
#endif // QT_CONFIG(tooltip)
        self.actionGit.setText(QCoreApplication.translate("MainWindow", u"Git", None))
#if QT_CONFIG(tooltip)
        self.actionGit.setToolTip(QCoreApplication.translate("MainWindow", u"Git", None))
#endif // QT_CONFIG(tooltip)
        self.actionGitHub.setText(QCoreApplication.translate("MainWindow", u"GitHub", None))
#if QT_CONFIG(tooltip)
        self.actionGitHub.setToolTip(QCoreApplication.translate("MainWindow", u"GitHub", None))
#endif // QT_CONFIG(tooltip)
        self.actionGraphViz.setText(QCoreApplication.translate("MainWindow", u"GraphViz", None))
#if QT_CONFIG(tooltip)
        self.actionGraphViz.setToolTip(QCoreApplication.translate("MainWindow", u"GraphViz", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(tooltip)
        self.actionHelp.setToolTip(QCoreApplication.translate("MainWindow", u"Help", None))
#endif // QT_CONFIG(tooltip)
        self.actionHTML.setText(QCoreApplication.translate("MainWindow", u"HTML", None))
#if QT_CONFIG(tooltip)
        self.actionHTML.setToolTip(QCoreApplication.translate("MainWindow", u"HTML", None))
#endif // QT_CONFIG(tooltip)
        self.actionImages.setText(QCoreApplication.translate("MainWindow", u"Images", None))
#if QT_CONFIG(tooltip)
        self.actionImages.setToolTip(QCoreApplication.translate("MainWindow", u"Images", None))
#endif // QT_CONFIG(tooltip)
        self.actioniOS.setText(QCoreApplication.translate("MainWindow", u"iOS", None))
#if QT_CONFIG(tooltip)
        self.actioniOS.setToolTip(QCoreApplication.translate("MainWindow", u"iOS", None))
#endif // QT_CONFIG(tooltip)
        self.actionJava.setText(QCoreApplication.translate("MainWindow", u"Java", None))
#if QT_CONFIG(tooltip)
        self.actionJava.setToolTip(QCoreApplication.translate("MainWindow", u"Java", None))
#endif // QT_CONFIG(tooltip)
        self.actionKDoc.setText(QCoreApplication.translate("MainWindow", u"KDoc", None))
#if QT_CONFIG(tooltip)
        self.actionKDoc.setToolTip(QCoreApplication.translate("MainWindow", u"KDoc", None))
#endif // QT_CONFIG(tooltip)
        self.actionKotlin.setText(QCoreApplication.translate("MainWindow", u"Kotlin", None))
#if QT_CONFIG(tooltip)
        self.actionKotlin.setToolTip(QCoreApplication.translate("MainWindow", u"Kotlin", None))
#endif // QT_CONFIG(tooltip)
        self.actionList.setText(QCoreApplication.translate("MainWindow", u"List", None))
#if QT_CONFIG(tooltip)
        self.actionList.setToolTip(QCoreApplication.translate("MainWindow", u"List", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
#if QT_CONFIG(tooltip)
        self.actionLoad.setToolTip(QCoreApplication.translate("MainWindow", u"Load", None))
#endif // QT_CONFIG(tooltip)
        self.actionMySql.setText(QCoreApplication.translate("MainWindow", u"MySQL", None))
#if QT_CONFIG(tooltip)
        self.actionMySql.setToolTip(QCoreApplication.translate("MainWindow", u"MySQL", None))
#endif // QT_CONFIG(tooltip)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"New", None))
#endif // QT_CONFIG(tooltip)
        self.actionNo.setText(QCoreApplication.translate("MainWindow", u"No", None))
#if QT_CONFIG(tooltip)
        self.actionNo.setToolTip(QCoreApplication.translate("MainWindow", u"No", None))
#endif // QT_CONFIG(tooltip)
        self.actionOverWrite.setText(QCoreApplication.translate("MainWindow", u"Over Write", None))
#if QT_CONFIG(tooltip)
        self.actionOverWrite.setToolTip(QCoreApplication.translate("MainWindow", u"Over Write", None))
#endif // QT_CONFIG(tooltip)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
        self.actionPaste.setToolTip(QCoreApplication.translate("MainWindow", u"Paste", None))
#endif // QT_CONFIG(tooltip)
        self.actionPhp.setText(QCoreApplication.translate("MainWindow", u"PHP", None))
#if QT_CONFIG(tooltip)
        self.actionPhp.setToolTip(QCoreApplication.translate("MainWindow", u"PHP", None))
#endif // QT_CONFIG(tooltip)
        self.actionPostgreSql.setText(QCoreApplication.translate("MainWindow", u"PostgreSql", None))
#if QT_CONFIG(tooltip)
        self.actionPostgreSql.setToolTip(QCoreApplication.translate("MainWindow", u"PostggreSql", None))
#endif // QT_CONFIG(tooltip)
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
#if QT_CONFIG(tooltip)
        self.actionPrint.setToolTip(QCoreApplication.translate("MainWindow", u"Print", None))
#endif // QT_CONFIG(tooltip)
        self.actionPython.setText(QCoreApplication.translate("MainWindow", u"Python", None))
#if QT_CONFIG(tooltip)
        self.actionPython.setToolTip(QCoreApplication.translate("MainWindow", u"Python", None))
#endif // QT_CONFIG(tooltip)
        self.actionQt.setText(QCoreApplication.translate("MainWindow", u"Qt", None))
#if QT_CONFIG(tooltip)
        self.actionQt.setToolTip(QCoreApplication.translate("MainWindow", u"Qt", None))
#endif // QT_CONFIG(tooltip)
        self.actionQtAbout.setText(QCoreApplication.translate("MainWindow", u"Qt About", None))
#if QT_CONFIG(tooltip)
        self.actionQtAbout.setToolTip(QCoreApplication.translate("MainWindow", u"Qt About", None))
#endif // QT_CONFIG(tooltip)
        self.actionQtDesigner.setText(QCoreApplication.translate("MainWindow", u"Qt Designer", None))
#if QT_CONFIG(tooltip)
        self.actionQtDesigner.setToolTip(QCoreApplication.translate("MainWindow", u"Qt Designer", None))
#endif // QT_CONFIG(tooltip)
        self.actionQtPython.setText(QCoreApplication.translate("MainWindow", u"Qt Python", None))
#if QT_CONFIG(tooltip)
        self.actionQtPython.setToolTip(QCoreApplication.translate("MainWindow", u"Qt Python", None))
#endif // QT_CONFIG(tooltip)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(tooltip)
        self.actionQuit.setToolTip(QCoreApplication.translate("MainWindow", u"Quit", None))
#endif // QT_CONFIG(tooltip)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.actionRename.setText(QCoreApplication.translate("MainWindow", u"Rename", None))
#if QT_CONFIG(tooltip)
        self.actionRename.setToolTip(QCoreApplication.translate("MainWindow", u"Rename", None))
#endif // QT_CONFIG(tooltip)
        self.actionReset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
#if QT_CONFIG(tooltip)
        self.actionReset.setToolTip(QCoreApplication.translate("MainWindow", u"Reset", None))
#endif // QT_CONFIG(tooltip)
        self.actionResourceCompiler.setText(QCoreApplication.translate("MainWindow", u"Resource Compiler", None))
#if QT_CONFIG(tooltip)
        self.actionResourceCompiler.setToolTip(QCoreApplication.translate("MainWindow", u"Resource Compiler", None))
#endif // QT_CONFIG(tooltip)
        self.actionRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
#if QT_CONFIG(tooltip)
        self.actionRun.setToolTip(QCoreApplication.translate("MainWindow", u"Run", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(tooltip)
        self.actionSaveAs.setToolTip(QCoreApplication.translate("MainWindow", u"Save As", None))
#endif // QT_CONFIG(tooltip)
        self.actionScript.setText(QCoreApplication.translate("MainWindow", u"Script", None))
#if QT_CONFIG(tooltip)
        self.actionScript.setToolTip(QCoreApplication.translate("MainWindow", u"Script", None))
#endif // QT_CONFIG(tooltip)
        self.actionSelect.setText(QCoreApplication.translate("MainWindow", u"Select", None))
#if QT_CONFIG(tooltip)
        self.actionSelect.setToolTip(QCoreApplication.translate("MainWindow", u"Select", None))
#endif // QT_CONFIG(tooltip)
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.actionSettings.setToolTip(QCoreApplication.translate("MainWindow", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionSqlLite.setText(QCoreApplication.translate("MainWindow", u"SQL Lite", None))
#if QT_CONFIG(tooltip)
        self.actionSqlLite.setToolTip(QCoreApplication.translate("MainWindow", u"SQL Lite", None))
#endif // QT_CONFIG(tooltip)
        self.actionStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
#if QT_CONFIG(tooltip)
        self.actionStart.setToolTip(QCoreApplication.translate("MainWindow", u"Start", None))
#endif // QT_CONFIG(tooltip)
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
#if QT_CONFIG(tooltip)
        self.actionStop.setToolTip(QCoreApplication.translate("MainWindow", u"Stop", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.actionUsb.setText(QCoreApplication.translate("MainWindow", u"USB", None))
#if QT_CONFIG(tooltip)
        self.actionUsb.setToolTip(QCoreApplication.translate("MainWindow", u"USB", None))
#endif // QT_CONFIG(tooltip)
        self.actionUserInterface.setText(QCoreApplication.translate("MainWindow", u"User Interface", None))
#if QT_CONFIG(tooltip)
        self.actionUserInterface.setToolTip(QCoreApplication.translate("MainWindow", u"User Interface", None))
#endif // QT_CONFIG(tooltip)
        self.actionVSCode.setText(QCoreApplication.translate("MainWindow", u"VS Code", None))
#if QT_CONFIG(tooltip)
        self.actionVSCode.setToolTip(QCoreApplication.translate("MainWindow", u"VS Code", None))
#endif // QT_CONFIG(tooltip)
        self.actionWrite.setText(QCoreApplication.translate("MainWindow", u"Write", None))
#if QT_CONFIG(tooltip)
        self.actionWrite.setToolTip(QCoreApplication.translate("MainWindow", u"Write", None))
#endif // QT_CONFIG(tooltip)
        self.actionWww.setText(QCoreApplication.translate("MainWindow", u"WWW", None))
#if QT_CONFIG(tooltip)
        self.actionWww.setToolTip(QCoreApplication.translate("MainWindow", u"WWW", None))
#endif // QT_CONFIG(tooltip)
        self.actionYes.setText(QCoreApplication.translate("MainWindow", u"Yes", None))
#if QT_CONFIG(tooltip)
        self.actionYes.setToolTip(QCoreApplication.translate("MainWindow", u"Tes", None))
#endif // QT_CONFIG(tooltip)
        self.actionAbort.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
#if QT_CONFIG(tooltip)
        self.actionAbort.setToolTip(QCoreApplication.translate("MainWindow", u"Abort", None))
#endif // QT_CONFIG(tooltip)
        self.actionConfigure.setText(QCoreApplication.translate("MainWindow", u"Configure", None))
#if QT_CONFIG(tooltip)
        self.actionConfigure.setToolTip(QCoreApplication.translate("MainWindow", u"Configure", None))
#endif // QT_CONFIG(tooltip)
        self.actionDia.setText(QCoreApplication.translate("MainWindow", u"Dia", None))
#if QT_CONFIG(tooltip)
        self.actionDia.setToolTip(QCoreApplication.translate("MainWindow", u"Dia", None))
#endif // QT_CONFIG(tooltip)
        self.actionPyQt.setText(QCoreApplication.translate("MainWindow", u"PyQt", None))
#if QT_CONFIG(tooltip)
        self.actionPyQt.setToolTip(QCoreApplication.translate("MainWindow", u"PyQt", None))
#endif // QT_CONFIG(tooltip)
        self.actionPySide.setText(QCoreApplication.translate("MainWindow", u"PySide", None))
#if QT_CONFIG(tooltip)
        self.actionPySide.setToolTip(QCoreApplication.translate("MainWindow", u"PySide", None))
#endif // QT_CONFIG(tooltip)
        self.actionMinimise.setText(QCoreApplication.translate("MainWindow", u"Minimise", None))
#if QT_CONFIG(tooltip)
        self.actionMinimise.setToolTip(QCoreApplication.translate("MainWindow", u"Minimise", None))
#endif // QT_CONFIG(tooltip)
        self.actionMaximise.setText(QCoreApplication.translate("MainWindow", u"Maximise", None))
#if QT_CONFIG(tooltip)
        self.actionMaximise.setToolTip(QCoreApplication.translate("MainWindow", u"Maximise", None))
#endif // QT_CONFIG(tooltip)
        self.actionContextHelp.setText(QCoreApplication.translate("MainWindow", u"Context Help", None))
#if QT_CONFIG(tooltip)
        self.actionContextHelp.setToolTip(QCoreApplication.translate("MainWindow", u"Context Help", None))
#endif // QT_CONFIG(tooltip)
        self.actionSetUp.setText(QCoreApplication.translate("MainWindow", u"Set Up", None))
#if QT_CONFIG(tooltip)
        self.actionSetUp.setToolTip(QCoreApplication.translate("MainWindow", u"Set Up", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuMinimise.setText(QCoreApplication.translate("MainWindow", u"Minimise", None))
        self.actionMenuMaximise.setText(QCoreApplication.translate("MainWindow", u"Maximise", None))
        self.actionMenuContextHelp.setText(QCoreApplication.translate("MainWindow", u"Context Help", None))
#if QT_CONFIG(tooltip)
        self.actionMenuContextHelp.setToolTip(QCoreApplication.translate("MainWindow", u"Context Help", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMenuContextHelp.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.actionMenuExit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMenuExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionMenuCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionMenuCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionMenuPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionMenuRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionMenuUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.actionMenuSelectAll.setText(QCoreApplication.translate("MainWindow", u"Select All", None))
#if QT_CONFIG(shortcut)
        self.actionMenuSelectAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionMenuSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionMenuSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuConfigure.setText(QCoreApplication.translate("MainWindow", u"Configure", None))
        self.actionMenuAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionMenuAboutQt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionMenuRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
#if QT_CONFIG(shortcut)
        self.actionMenuRun.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MainWindow", u"&Settings", None))
        self.menu_Window.setTitle(QCoreApplication.translate("MainWindow", u"&Window", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menu_Build.setTitle(QCoreApplication.translate("MainWindow", u"&Build", None))
        self.toolBarSmall.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBarSmall", None))
    # retranslateUi

