# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QTabWidget, QToolBar,
    QVBoxLayout, QWidget)
import splash_rc
import buttons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(630, 500)
        MainWindow.setMinimumSize(QSize(630, 500))
        MainWindow.setMaximumSize(QSize(16777215, 16777215))
        icon = QIcon()
        icon.addFile(u":/images/images/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon1 = QIcon()
        icon1.addFile(u":/glass/buttons/glassButtonExit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon1)
        self.actionLight = QAction(MainWindow)
        self.actionLight.setObjectName(u"actionLight")
        self.actionLight.setCheckable(True)
        self.actionDark = QAction(MainWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.actionDark.setCheckable(True)
        self.actionAuto = QAction(MainWindow)
        self.actionAuto.setObjectName(u"actionAuto")
        self.actionAuto.setCheckable(True)
        self.actionTheme = QAction(MainWindow)
        self.actionTheme.setObjectName(u"actionTheme")
        icon2 = QIcon()
        icon2.addFile(u":/glass/buttons/glassButtonTheme.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTheme.setIcon(icon2)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon3 = QIcon()
        icon3.addFile(u":/glass/buttons/glassButtonAbout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAboutQt = QAction(MainWindow)
        self.actionAboutQt.setObjectName(u"actionAboutQt")
        icon4 = QIcon()
        icon4.addFile(u":/glass/buttons/glassButtonQt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAboutQt.setIcon(icon4)
        self.actionHTML = QAction(MainWindow)
        self.actionHTML.setObjectName(u"actionHTML")
        icon5 = QIcon()
        icon5.addFile(u":/glass/buttons/glassButtonHtml.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionHTML.setIcon(icon5)
        self.actionPHP = QAction(MainWindow)
        self.actionPHP.setObjectName(u"actionPHP")
        icon6 = QIcon()
        icon6.addFile(u":/glass/buttons/glassButtonPhp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPHP.setIcon(icon6)
        self.actionPython = QAction(MainWindow)
        self.actionPython.setObjectName(u"actionPython")
        icon7 = QIcon()
        icon7.addFile(u":/glass/buttons/glassButtonPython.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPython.setIcon(icon7)
        self.actionArduino = QAction(MainWindow)
        self.actionArduino.setObjectName(u"actionArduino")
        icon8 = QIcon()
        icon8.addFile(u":/glass/buttons/glassButtonArduino.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionArduino.setIcon(icon8)
        self.actionBash = QAction(MainWindow)
        self.actionBash.setObjectName(u"actionBash")
        icon9 = QIcon()
        icon9.addFile(u":/glass/buttons/glassButtonBash.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBash.setIcon(icon9)
        self.actionKotlin = QAction(MainWindow)
        self.actionKotlin.setObjectName(u"actionKotlin")
        icon10 = QIcon()
        icon10.addFile(u":/glass/buttons/glassButtonKotlin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionKotlin.setIcon(icon10)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayoutMain = QVBoxLayout()
        self.verticalLayoutMain.setObjectName(u"verticalLayoutMain")
        self.verticalLayoutMain.setContentsMargins(0, -1, -1, -1)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")

        self.verticalLayoutMain.addWidget(self.tabWidget)


        self.verticalLayout_2.addLayout(self.verticalLayoutMain)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 630, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuTheme = QMenu(self.menuFile)
        self.menuTheme.setObjectName(u"menuTheme")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setMinimumSize(QSize(0, 0))
        self.toolBar.setBaseSize(QSize(0, 48))
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(Qt.BottomToolBarArea|Qt.TopToolBarArea)
        self.toolBar.setIconSize(QSize(48, 48))
        self.toolBar.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.toolBarApps = QToolBar(MainWindow)
        self.toolBarApps.setObjectName(u"toolBarApps")
        self.toolBarApps.setEnabled(True)
        self.toolBarApps.setBaseSize(QSize(96, 0))
        self.toolBarApps.setMovable(True)
        self.toolBarApps.setAllowedAreas(Qt.LeftToolBarArea|Qt.RightToolBarArea)
        self.toolBarApps.setIconSize(QSize(96, 96))
        self.toolBarApps.setFloatable(False)
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBarApps)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.menuTheme.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addAction(self.actionDark)
        self.menuTheme.addAction(self.actionAuto)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQt)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addAction(self.actionTheme)
        self.toolBarApps.addAction(self.actionBash)
        self.toolBarApps.addAction(self.actionHTML)
        self.toolBarApps.addAction(self.actionPHP)
        self.toolBarApps.addAction(self.actionPython)
        self.toolBarApps.addAction(self.actionArduino)
        self.toolBarApps.addAction(self.actionKotlin)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Projectionist", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"E&xit", None))
#if QT_CONFIG(tooltip)
        self.actionExit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit Projectionist", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionExit.setStatusTip(QCoreApplication.translate("MainWindow", u"Exit Projectionist", None))
#endif // QT_CONFIG(statustip)
        self.actionLight.setText(QCoreApplication.translate("MainWindow", u"Light", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.actionAuto.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.actionTheme.setText(QCoreApplication.translate("MainWindow", u"&Theme", None))
#if QT_CONFIG(tooltip)
        self.actionTheme.setToolTip(QCoreApplication.translate("MainWindow", u"Change Theme", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionTheme.setStatusTip(QCoreApplication.translate("MainWindow", u"Change Application Theme", None))
#endif // QT_CONFIG(statustip)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAboutQt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionHTML.setText(QCoreApplication.translate("MainWindow", u"HTML", None))
#if QT_CONFIG(tooltip)
        self.actionHTML.setToolTip(QCoreApplication.translate("MainWindow", u"HTML Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionPHP.setText(QCoreApplication.translate("MainWindow", u"PHP", None))
#if QT_CONFIG(tooltip)
        self.actionPHP.setToolTip(QCoreApplication.translate("MainWindow", u"PHP Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionPython.setText(QCoreApplication.translate("MainWindow", u"Python", None))
#if QT_CONFIG(tooltip)
        self.actionPython.setToolTip(QCoreApplication.translate("MainWindow", u"Pyhton Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionArduino.setText(QCoreApplication.translate("MainWindow", u"Arduino", None))
#if QT_CONFIG(tooltip)
        self.actionArduino.setToolTip(QCoreApplication.translate("MainWindow", u"Arduino Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionBash.setText(QCoreApplication.translate("MainWindow", u"Bash", None))
#if QT_CONFIG(tooltip)
        self.actionBash.setToolTip(QCoreApplication.translate("MainWindow", u"Bash Project", None))
#endif // QT_CONFIG(tooltip)
        self.actionKotlin.setText(QCoreApplication.translate("MainWindow", u"Kotlin", None))
#if QT_CONFIG(tooltip)
        self.actionKotlin.setToolTip(QCoreApplication.translate("MainWindow", u"Kotlin Project", None))
#endif // QT_CONFIG(tooltip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.toolBarApps.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBarApps", None))
    # retranslateUi

